name: evogym
channels:
  - defaults
dependencies:
  - python=3.7.11
  - pip
  - pip:
    - glfw==2.5.0
    - gpy==1.10.0
    - git+git://github.com/yunshengtian/neat-python@2762ab630838520ca6c03a866e8a158f592b0370
    - gym==0.19.0
    - h5py==3.6.0
    - imageio==2.14.1
    - matplotlib==3.5.1
    - git+git://github.com/yunshengtian/GPyOpt@5fc1188ffdefea9a3bc7964a9414d4922603e904
    - numpy==1.21.5
    - opencv-python==4.5.5.62
    - pillow==9.0.0
    - pybind11==2.9.0
    - pygifsicle==1.0.5
    - pyopengl==3.1.5
    - pyopengl-accelerate==3.1.5
    - stable-baselines3==1.4.0
    - torch==1.10.2
    - ttkbootstrap==1.5.1
    - typing==3.7.4.3

